# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: odds_crud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fodds_crud.proto\"\xd4\x01\n\x08\x44\x61taDict\x12\x0e\n\x06league\x18\x01 \x01(\t\x12\x11\n\thome_team\x18\x02 \x01(\t\x12\x11\n\taway_team\x18\x03 \x01(\t\x12\x1a\n\x12home_team_win_odds\x18\x04 \x01(\x02\x12\x1a\n\x12\x61way_team_win_odds\x18\x05 \x01(\x02\x12\x11\n\tdraw_odds\x18\x06 \x01(\x02\x12\x11\n\tgame_date\x18\x07 \x01(\t\x12\x0f\n\x07odds_id\x18\x08 \x01(\t\x12\x12\n\ndate_range\x18\t \x01(\t\x12\x0f\n\x07user_id\x18\n \x01(\t\"F\n\nDBResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\t.DataDict2\xaa\x01\n\x08OddsCrud\x12&\n\nCreateOdds\x12\t.DataDict\x1a\x0b.DBResponse\"\x00\x12&\n\x08ReadOdds\x12\t.DataDict\x1a\x0b.DBResponse\"\x00\x30\x01\x12&\n\nUpdateOdds\x12\t.DataDict\x1a\x0b.DBResponse\"\x00\x12&\n\nDeleteOdds\x12\t.DataDict\x1a\x0b.DBResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'odds_crud_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATADICT._serialized_start=20
  _DATADICT._serialized_end=232
  _DBRESPONSE._serialized_start=234
  _DBRESPONSE._serialized_end=304
  _ODDSCRUD._serialized_start=307
  _ODDSCRUD._serialized_end=477
# @@protoc_insertion_point(module_scope)
